/**
 * Standard resources/services that non-profits commonly offer or need.
 * Grouped by category for easier browsing in the UI.
 */

export const RESOURCE_CATEGORIES: Record<string, string[]> = {
  'Funding & Finance': [
    'Grant Writing Assistance',
    'Fundraising Support',
    'Financial Planning',
    'Accounting Services',
    'Tax Preparation',
    'Fiscal Sponsorship',
    'Micro-Grants',
    'Donor Database Management',
    'Crowdfunding Support',
    'Budget Training',
  ],
  'Capacity Building': [
    'Strategic Planning',
    'Board Development',
    'Leadership Training',
    'Organizational Development',
    'Program Evaluation',
    'Impact Measurement',
    'Succession Planning',
    'Change Management',
    'Staff Training & Development',
    'Volunteer Management Training',
  ],
  'Technology & Digital': [
    'Website Development',
    'Social Media Management',
    'IT Support',
    'Database Management',
    'Cybersecurity',
    'Digital Marketing',
    'Email Marketing',
    'Graphic Design',
    'Video Production',
    'App Development',
  ],
  'Legal & Compliance': [
    'Legal Counsel',
    'Regulatory Compliance',
    'Nonprofit Incorporation',
    '501(c)(3) Application Help',
    'Contract Review',
    'Intellectual Property',
    'Employment Law Guidance',
    'Policy Development',
    'Insurance Guidance',
    'Risk Management',
  ],
  'Human Resources': [
    'Volunteer Recruitment',
    'Staff Recruitment',
    'HR Consulting',
    'Background Checks',
    'Payroll Services',
    'Benefits Administration',
    'Diversity & Inclusion Training',
    'Conflict Resolution',
    'Team Building',
    'Internship Programs',
  ],
  'Marketing & Communications': [
    'Branding & Identity',
    'Public Relations',
    'Content Writing',
    'Print Design & Materials',
    'Photography Services',
    'Translation Services',
    'Event Promotion',
    'Newsletter Production',
    'Media Relations',
    'Storytelling & Advocacy',
  ],
  'Community & Outreach': [
    'Community Organizing',
    'Event Planning & Hosting',
    'Meeting Space',
    'Transportation Services',
    'Food & Catering',
    'Childcare Services',
    'Interpretation Services',
    'Community Needs Assessment',
    'Referral Network',
    'Crisis Intervention',
  ],
  'Program & Service Delivery': [
    'Mentoring Programs',
    'Tutoring & Education',
    'Job Training & Placement',
    'Health Screening',
    'Mental Health Counseling',
    'Substance Abuse Services',
    'Housing Assistance',
    'Food Distribution',
    'Clothing Distribution',
    'Youth Programming',
  ],
  'Physical Resources': [
    'Office Space',
    'Storage Space',
    'Equipment Lending',
    'Vehicle Access',
    'Kitchen Facilities',
    'Computer Lab Access',
    'Printing & Copying',
    'Warehouse Space',
    'Land & Garden Space',
    'Shared Workspace',
  ],
  'Research & Data': [
    'Data Collection',
    'Data Analysis',
    'Survey Design',
    'Research Partnerships',
    'GIS Mapping',
    'Census Outreach',
    'Academic Collaboration',
    'Report Writing',
    'Best Practices Sharing',
    'Knowledge Management',
  ],
};

/** Flat list of all standard resource names. */
export const STANDARD_RESOURCES: string[] = Object.values(RESOURCE_CATEGORIES).flat();

/** Organization size options. */
export const ORG_SIZES = [
  { value: 'small', label: 'Small', description: 'Under 10 staff, mostly volunteers' },
  { value: 'medium', label: 'Medium', description: '10–50 staff, established programs' },
  { value: 'large', label: 'Large', description: '50+ staff, multiple programs & locations' },
] as const;
